# Generated by Django 3.2.6 on 2021-08-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
  
    ]
